# SIPTA Notebook: Ingestión de datos — Salud

## Dominio: Salud

Este notebook documenta la ingesta reproducible del dataset oficial
**Instituciones de Salud con servicios de urgencias en Bogotá D.C.**

### Objetivos

- Cargar el archivo original almacenado en `data/raw/SALUD`.
- Preservar el archivo crudo sin modificaciones.
- Identificar la codificación y estructura necesarias para su lectura.
- Registrar dimensiones, columnas y tipos iniciales.
- Verificar que el dataset queda disponible para la fase posterior de validación.

> En este notebook no se realizan limpieza, integración territorial ni cálculo de indicadores.

In [1]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent
RAW_DIR = PROJECT_ROOT / "data" / "raw"
SALUD_DIR = RAW_DIR / "SALUD"

archivo_salud = SALUD_DIR / "osb_ofertasrv-ips-urgencias.csv"

print("PROJECT_ROOT:", PROJECT_ROOT)
print("Archivo Salud:", archivo_salud)
print("¿Existe?:", archivo_salud.exists())

PROJECT_ROOT: c:\DataJam_DataOlinguitos_Gen
Archivo Salud: c:\DataJam_DataOlinguitos_Gen\data\raw\SALUD\osb_ofertasrv-ips-urgencias.csv
¿Existe?: True

In [2]:
print("=== ARCHIVO ORIGINAL ===")
print("Nombre:", archivo_salud.name)
print("Tamaño (MB):", round(archivo_salud.stat().st_size / (1024**2), 3))

=== ARCHIVO ORIGINAL ===
Nombre: osb_ofertasrv-ips-urgencias.csv
Tamaño (MB): 0.015

In [3]:
df_salud = pd.read_csv(
    archivo_salud,
    sep=None,
    engine="python",
    encoding="cp1252"
)

df_salud.head()

,OBJECTID,Código IPS,Nombre IPS,Nombre sede,Número sede,Dirección,Telefono contacto,Correco electrónico,Tipo de naturaleza,Latitud,Longitud
0,1,1100105322,Clínica La Inmaculada,Clínica la Inmaculada,1,KR 7 68 70,5870366,inmaculada@clinicalainmaculada.org,Privada,"4,65319721","-74,05726314"
1,2,1100105597,Centro De Atención En Salud Cafam Floresta,Centro de Atención en Salud Cafam Floresta,4,AK 68 90 88,5550700 ext 12017-12015,calidadsalud@cafam.com.co,Privada,"4,685731816","-74,07440845"
2,3,1100105597,Centro De Atención En Salud Cafam Suba,Centro de Atención en Salud Cafam Suba,11,KR 113 C 142 A 98,5550700 ext 12017-12015,calidadsalud@cafam.com.co,Privada,"4,74833602","-74,10322024"
3,4,1100105618,Fundación Santa Fe De Bogotá,Fundación Santa Fe de Bogotá,1,CL 119 7 75,6030303 ext. 5105,adriana.urrego@fsfb.org.co,Privada,"4,695541649","-74,03319001"
4,5,1100105668,Hospital Universitario Clínica San Rafael,Hospital Universitario Clínica San Rafael,1,KR 8 17 45 SUR,7464714 EXT. 2740,direcciongeneral1@stewardcolombia.org,Privada,"4,576655061","-74,09131428"

In [4]:
print("=== DIMENSIONES DEL DATASET ===")
print(f"Filas: {df_salud.shape[0]}")
print(f"Columnas: {df_salud.shape[1]}")

=== DIMENSIONES DEL DATASET ===
Filas: 84
Columnas: 11

In [5]:
print("=== COLUMNAS ===")

for i, columna in enumerate(df_salud.columns, start=1):
    print(f"{i}. {columna}")

=== COLUMNAS ===
1. OBJECTID
2. Código IPS
3. Nombre IPS
4. Nombre sede
5. Número sede
6. Dirección
7. Telefono contacto
8. Correco electrónico
9. Tipo de naturaleza
10. Latitud
11. Longitud

In [6]:
print("=== TIPOS DE DATOS ORIGINALES ===")
print(df_salud.dtypes)

=== TIPOS DE DATOS ORIGINALES ===
OBJECTID               int64
Código IPS             int64
Nombre IPS               str
Nombre sede              str
Número sede            int64
Dirección                str
Telefono contacto        str
Correco electrónico      str
Tipo de naturaleza       str
Latitud                  str
Longitud                 str
dtype: object

In [7]:
print("=== PRIMERAS 5 FILAS ===")
display(df_salud.head())

print("\n=== ÚLTIMAS 5 FILAS ===")
display(df_salud.tail())

=== PRIMERAS 5 FILAS ===

,OBJECTID,Código IPS,Nombre IPS,Nombre sede,Número sede,Dirección,Telefono contacto,Correco electrónico,Tipo de naturaleza,Latitud,Longitud
0,1,1100105322,Clínica La Inmaculada,Clínica la Inmaculada,1,KR 7 68 70,5870366,inmaculada@clinicalainmaculada.org,Privada,"4,65319721","-74,05726314"
1,2,1100105597,Centro De Atención En Salud Cafam Floresta,Centro de Atención en Salud Cafam Floresta,4,AK 68 90 88,5550700 ext 12017-12015,calidadsalud@cafam.com.co,Privada,"4,685731816","-74,07440845"
2,3,1100105597,Centro De Atención En Salud Cafam Suba,Centro de Atención en Salud Cafam Suba,11,KR 113 C 142 A 98,5550700 ext 12017-12015,calidadsalud@cafam.com.co,Privada,"4,74833602","-74,10322024"
3,4,1100105618,Fundación Santa Fe De Bogotá,Fundación Santa Fe de Bogotá,1,CL 119 7 75,6030303 ext. 5105,adriana.urrego@fsfb.org.co,Privada,"4,695541649","-74,03319001"
4,5,1100105668,Hospital Universitario Clínica San Rafael,Hospital Universitario Clínica San Rafael,1,KR 8 17 45 SUR,7464714 EXT. 2740,direcciongeneral1@stewardcolombia.org,Privada,"4,576655061","-74,09131428"

=== ÚLTIMAS 5 FILAS ===

,OBJECTID,Código IPS,Nombre IPS,Nombre sede,Número sede,Dirección,Telefono contacto,Correco electrónico,Tipo de naturaleza,Latitud,Longitud
79,80,1100134552,Sociedad Medica Alcalá Sas,Sociedad Medica Alcalá SAS,1,AK 19 135 24,3232255717-3114849286,calidad@smaclinica.com,Privada,"4,72003429","-74,04646443"
80,81,1100135025,Clínica Nueva El Lago S.A.S - Sede Calle 76,Clínica Nueva El Lago S.A.S - Sede Calle 76,1,CL 76 15 55,3078061 - 3123459128,info@clinicanuevaellago.com,Privada,"4,662943844","-74,05967674"
81,82,1100136278,Clínica Azul,Clínica Azul,1,KR 49 D 91 33,3184871071,calidadca@clinicaazul.co,Privada,"4,679864053","-74,06447125"
82,83,1100136300,Central De Urgencias Norte,Central de Urgencias Norte,32,CL 163 A 22 22,6466060 Ext 5719469,mnempeque@epssanitas.com,Privada,"4,744373714","-74,04641604"
83,84,1100136300,Unidad De Urgencias Puente Aranda,Unidad de Urgencias Puente Aranda,33,KR 62 14 41,6466060,mnempeque@epssanitas.com,Privada,"4,634554599","-74,11244064"

## Fuente y trazabilidad

**Dataset:** Instituciones de Salud con servicios de urgencias en Bogotá D.C.  
**Entidad:** Secretaría Distrital de Salud — Bogotá D.C.  
**Fuente:** Portal de Datos Abiertos de Bogotá  
**Archivo local:** `data/raw/SALUD/osb_ofertasrv-ips-urgencias.csv`

### Características técnicas observadas

- Formato: CSV.
- Codificación utilizada para lectura: `cp1252`.
- Registros cargados: 84.
- Variables: 11.
- El archivo se conserva en `data/raw/SALUD` sin modificaciones manuales.
- Las columnas `Latitud` y `Longitud` permiten evaluar posteriormente su asociación con la unidad territorial `Localidad`.

### Alcance de esta etapa

La ingesta únicamente comprueba que el dataset original puede cargarse de forma reproducible.

La evaluación de nulos, duplicados, unicidad de sede, calidad de coordenadas y cobertura territorial se realiza en `02_validation_salud.ipynb`.